const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

function buildInvoiceEmail(invoice, options) {
  const { kind, mode, to, subject, message } = options;
  if (!['invoice', 'receipt'].includes(kind) || !['email', 'pdf', 'both'].includes(mode)) throw new Error('Choose a document and delivery format.');
  if (kind === 'receipt' && !invoice.paid) throw new Error('Mark this invoice paid before issuing a receipt.');
  if (!/^[^\s@<>;,]+@[^\s@<>;,]+\.[^\s@<>;,]+$/.test(to) || /[\r\n]/.test(subject) || !subject.trim() || subject.length > 160 || message.length > 5000) throw new Error('Check the email address, subject, and message length.');
  const items = invoice.items || [];
  const subtotal = items.reduce((sum, item) => sum + Number(item.qty || 0) * Number(item.unitPrice || 0), 0);
  const tax = subtotal * Number(invoice.taxRate || 0);
  const total = subtotal + tax;
  if (![subtotal, tax, total].every(Number.isFinite)) throw new Error('Check the invoice amounts.');
  const money = value => `${invoice.currency || '$'}${value.toFixed(2)}`;
  const title = kind === 'receipt' ? 'Adoption payment receipt' : 'Adoption invoice';
  const seller = invoice.seller || {};
  const buyer = invoice.adoptingParent || {};
  const puppy = Object.entries(invoice.puppy || {}).filter(([,value]) => value).map(([key,value]) => `${key}: ${value}`).join(' · ');
  const lines = items.map(item => `${item.description}: ${item.qty} × ${money(Number(item.unitPrice || 0))} = ${money(Number(item.qty || 0) * Number(item.unitPrice || 0))}`);
  const summary = [title, `Invoice reference: ${invoice.invoiceNumber}`, `Issued: ${invoice.issueDate || String(invoice.createdAt || '').slice(0,10)}`, `Breeder: ${seller.name || 'ImperialPaws'}`, `Adopting parent: ${buyer.name || ''}`, puppy, ...lines, `Subtotal: ${money(subtotal)}`, `Tax: ${money(tax)}`, `Total: ${money(total)}`, `Payment recorded: ${money(invoice.paid ? total : 0)}`, `Balance due: ${money(invoice.paid ? 0 : total)}`, invoice.notes || ''];
  const cell = 'padding:12px 8px;border-bottom:1px solid #e6dfd1;text-align:left;';
  const details = `<h2 style="font:26px Georgia,serif;color:#263e31;">${title}</h2><p>Reference <strong>${escape(invoice.invoiceNumber)}</strong><br>Issued: ${escape(invoice.issueDate || String(invoice.createdAt || '').slice(0,10))}${invoice.dueDate && !invoice.paid ? '<br>Due: '+escape(invoice.dueDate) : ''}</p><p style="color:#496048;">${invoice.paid ? 'PAID IN FULL' : 'PAYMENT PENDING'}</p><table role="presentation" width="100%"><tr><td style="vertical-align:top;width:50%;padding:12px 8px;"><strong>Breeder / seller</strong><br>${['name','address','email','phone'].map(k => escape(seller[k])).filter(Boolean).join('<br>')}</td><td style="vertical-align:top;padding:12px 8px;"><strong>Adopting parent</strong><br>${['name','address','city','state','zip','email'].map(k => escape(buyer[k])).filter(Boolean).join('<br>')}</td></tr></table>${puppy ? '<p style="background:#f3eee3;padding:16px;">🐾 '+escape(puppy)+'</p>' : ''}<table width="100%" cellspacing="0" style="border-collapse:collapse;font-size:14px;"><tr><th style="${cell}">Adoption fee / agreed charge</th><th style="${cell}text-align:right;white-space:nowrap;">Amount</th></tr>${items.map(item => `<tr><td style="${cell}">${escape(item.description)}<br><small>${escape(item.qty)} × ${escape(money(Number(item.unitPrice || 0)))}</small></td><td style="${cell}text-align:right;white-space:nowrap;">${escape(money(Number(item.qty || 0) * Number(item.unitPrice || 0)))}</td></tr>`).join('')}${[['Subtotal',subtotal],['Tax',tax],['Total adoption charges',total],['Payment recorded',invoice.paid ? total : 0],['Balance due',invoice.paid ? 0 : total]].map(([label,value]) => `<tr><td style="${cell}">${label}</td><td style="${cell}text-align:right;white-space:nowrap;"><strong>${escape(money(value))}</strong></td></tr>`).join('')}</table>${invoice.notes ? '<p style="white-space:pre-line;">'+escape(invoice.notes)+'</p>' : ''}<p style="font-size:12px;color:#68756b;">Keep this ${kind} with your adoption agreement and puppy records.</p>`;
  const attachmentNote = mode !== 'email' ? `Your ${kind} PDF is attached to this email.` : '';
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;background:#f3f0e9;font:15px Arial,sans-serif;color:#293b31;overflow-wrap:anywhere;word-break:break-word;"><table role="presentation" width="100%" cellspacing="0"><tr><td style="padding:24px 12px;"><table role="presentation" width="100%" cellspacing="0" style="max-width:640px;table-layout:fixed;margin:auto;background:#fffdf8;border:1px solid #e6dfd1;"><tr><td style="padding:26px;background:#263e31;color:#eddcb2;font:24px Georgia,serif;">🐾 ${escape(seller.name || 'ImperialPaws')}<p style="font:11px Arial,sans-serif;letter-spacing:2px;">PUPPY PLACEMENT &amp; ADOPTION</p></td></tr><tr><td style="padding:20px;line-height:1.6;"><p>Hello ${escape(buyer.name || 'there')},</p><p>${escape(message).replace(/\n/g,'<br>')}</p>${mode === 'pdf' ? '<h2>'+title+'</h2><p>Reference: '+escape(invoice.invoiceNumber)+'</p>' : details}${attachmentNote ? '<p>'+attachmentNote+'</p>' : ''}<p>Warm regards,<br>${escape(seller.name || 'ImperialPaws')}</p></td></tr></table></td></tr></table></body></html>`;
  return { to, subject, html, text: [`Hello ${buyer.name || 'there'},`,message, ...(mode === 'pdf' ? [title, invoice.invoiceNumber] : summary),attachmentNote, seller.name || 'ImperialPaws'].filter(Boolean).join('\n\n') };
}
module.exports = { buildInvoiceEmail };
